###############################################################################
## FUNCTION     loadactivitydata
##
## DESCRIPTION  downloads the UCI HAR dataset as 'HAR.zip', unzips the file,
##              loads the test and training sets, labels the variables, adds
##              a factor with 6 levels for the activity performed during data
##              collection, adds the subjects ID number for each datapoint then
##              joins the two datasets together and returns the resulting tidy
##              dataset.
##
## ASSUMPTIONS  the function assumes that there are 561 variables in test test
##              and training datasets
##
## INPUT        path    - working directory containing the HAR Dataset
##              verbose - sets whether the function outputs status messages
##                        default value is FALSE
##              DL      - sets whether the dataset should be downloaded. The
##                        default value is FALSE
##
## RETURN       tidy dataset as a data frame with 563 variables
###############################################################################
loadactivitydata <- function(path="~/Dev/Coursera/cleaning/GetCleanData-Project/",verbose=FALSE,DL=FALSE){
    ## set the working directory based on the 'path' variable
    setwd(path)
    ## set the URL for downloading the dataset zip file
    fileURL="https://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.zip"
    ## set the number of columns in the datasets to be 561
    DATACOLS <- 561
    
    ## Check if asked to download the file
    if(DL){
        ## tell the user that the file is going to download
        message("Downloading the UCI HAR Dataset...",appendLF=FALSE)
        ## download the file and output status depending on value of 'verbose'
        download.file(url = fileURL,destfile="HAR.zip",method="curl",quiet=TRUE)
        ## tell the user that the file is done downloading
        message("SUCCESS!")
    }
    ## attempt to unzip the file 'HAR.zip'
    tryCatch({
        if(verbose){message("Unzipping dataset...",appendLF=FALSE)}
        unzip("HAR.zip")
    ## catch any warning messages generated by unzip and display in console
    }, warning=function(w){
        message("\nWARNING: Cannot unzip dataset")
        if(!file.exists("HAR.zip")){
            message("'HAR.zip' does not exist. Try running loadactivitydata with DL=TRUE?")
        }
        message("Message from unzip:\n  ",w)
        stop()
    ## catch any error messages generated by unzip and display in console
    }, error=function(e){
        message("ERROR: ",e)
    })
    ## tell the user that the unzip was successful
    if(verbose){message("SUCCESS!")}
    
    ## Tell user that training dataset is loading if in VERBOSE mode
    if(verbose){message("Loading training data set...",appendLF=FALSE)}

    ## calculate the number of lines in the test dataset file
    train_num_lines <- length(readLines("./UCI HAR Dataset/train/X_train.txt"))
    
    ## load the training data set
    train_data_set <- read.table("./UCI HAR Dataset/train/X_train.txt"
                                 ,nrows=train_num_lines
                                 ,comment.char=""
                                 ,colClasses="numeric")

    ## Tell user that training dataset load complete if in VERBOSE mode
    if(verbose){message("DONE!")}
    
    ## Tell user that test dataset is loading if in VERBOSE mode
    if(verbose){message("Loading testing data set...",appendLF=FALSE)}
    
    ## calculate the number of lines in the test dataset file
    test_num_lines <- length(readLines("./UCI HAR Dataset/test/X_test.txt"))
    
    ## load the test data set
    test_data_set <- read.table("./UCI HAR Dataset/test/X_test.txt"
                                ,nrows=test_num_lines
                                ,comment.char=""
                                ,colClasses="numeric")
    ## Tell user that test dataset load complete if in VERBOSE mode
    if(verbose){message("DONE!")}
    
    ## Tell user that that we're going to add labels and tidy up data if in VERBOSE mode
    if(verbose){message("Loading metadata and tidying up the dataset...",appendLF=FALSE)}
            
    ## load the activity level for each datapoint (represented as a 1 through 6)
    train_activity <- read.table("./UCI HAR Dataset/train/y_train.txt",colClasses="numeric")[,1]
    test_activity <- read.table("./UCI HAR Dataset/test/y_test.txt",colClasses="numeric")[,1]
    
    ## load the factor labels for the 6 different activities
    activity_labels <- read.table("./UCI HAR Dataset/activity_labels.txt",colClasses = c("numeric","character"))
    
    ## convert the activity integer vectors into factors with levels 1:6 from
    ## train_activiy or test_activity accordingly and labels from activity_labels
    train_activity <- factor(train_activity,activity_labels[,1],activity_labels[,2])
    train_data_set <- cbind(train_data_set,train_activity)
    
    test_activity <- factor(test_activity,activity_labels[,1],activity_labels[,2])
    test_data_set <- cbind(test_data_set,test_activity)

    ## load subject number annotations for each datapoint
    train_subjects <- read.table("./UCI HAR Dataset/train/subject_train.txt")
    test_subjects <- read.table("./UCI HAR Dataset/test/subject_test.txt")
    
    ## apply the subject number annotations to each data set separately
    train_data_set <- cbind(train_data_set,train_subjects)
    test_data_set <- cbind(test_data_set,test_subjects)

    ## load the column headers from 'features.txt'
    feature_names <- read.table("./UCI HAR Dataset/features.txt"
                                ,colClasses = "character")[,2]
    
    ## remove '(' , ')' , and '-' from the column header names
    feature_names <- gsub("(\\(|\\))|-",x=feature_names,replacement="")  
    
    ## add the vector to each dataset separately
    colnames(train_data_set) <- c(feature_names,"activity","subjectNum")
    colnames(test_data_set) <- c(feature_names,"activity","subjectNum")
    
    ## tell the user that tidying up is done if in VERBOSE mode
    if(verbose){message("DONE!")}

    ## tell the user that we're going to merge the datasets if in VERBOSE mode
    if(verbose){message("Combining data sets and subseting...",appendLF=FALSE)}
    
    ## row bind the two datasets together
    data<-rbind(test_data_set,train_data_set)
    
    ## explicitly remove the originally separate datasets after combining
    rm(test_data_set,train_data_set)
    ## tell the user that merge of datasets is done if in VERBOSE mode
    if(verbose){message("DONE!")}
    
    ## return the tidy dataset
    data
}

## load the data using the loadactivity function define above. We'll set the
## function to run in verbose mode and to download the file to demonstrate the
## functionality
data <- loadactivitydata(verbose=TRUE,DL=FALSE)

## subset the data using a regular expression that evaluates the variable header
## names for partial matches to any one of the following strings: 'mean','std',
## 'subj','activ' to return the subset of the data that is only mean and standard
## deviation values, the subject number, and the activity factor for each data
## point. We ignore the variables with 'Mean' in the name as they are not truely
## mean values.
dataMeansStds <- data[,grep("(mean|std)|(subj|activ)",names(data))]

## load the reshape library
library(reshape2)

## create a melt data frame keeping subjectNum and activity as id variables and
## melting the measurement variables into 'variable'
dataMelt <- melt(dataMeansStds, id = c("subjectNum","activity"))

## remove the intermediary 'dataMeanStds' variable from our workspace
rm(dataMeansStds)

## cast the melted data frame to a new tidy dataframe conditioned on subjectNum
## and activity
dataMeans <- dcast(dataMelt,subjectNum + activity ~ variable,mean)

## remove the intermediary melted 'dataMelt' variable
rm(dataMelt)

## write the tidy dataset 'dataMeans' to a file named 'tidy_data.txt'
write.table(dataMeans,file="tidy_data.txt",row.name=FALSE)
